name: Auto-update agenda
on:
 schedule:
   - cron: "0 */6 * * *"
jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.SOC2FORGE_AUTOUPDATE_SSH_PRIVATE_KEY }}
      - uses: conda-incubator/setup-miniconda@v3.0.2
        with:
          soc2forge-variant: Soc2forge3
          environment-file: .github/actions/autoupdate/environment.yml
      - run: python .github/actions/autoupdate/update.py
      - name: Create Pull Request
        id: cpr
        # This is the v3 tag but for security purposes we pin to the exact commit.
        uses: peter-evans/create-pull-request@153407881ec5c347639a548ade7d8ad1d6740e38
        with:
          commit-message: "Update agenda version"
          title: "Update agenda version"
          body: |
            This PR was created by the autoupdate action as it detected that
            the agenda version has changed and thus should be updated
            in the configuration.

            Due to limitations of Github Actions, you will need to close/reopen
            the PR to get the actions running.
          branch: autoupdate-action
          delete-branch: true
