name: Build soc2forge
on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.SOC2FORGE_NAME }}-${{ matrix.OS_NAME }}-${{ matrix.ARCH }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            ARCH: x86_64
            TARGET_PLATFORM: win-64
            SOC2FORGE_NAME: "Soc2forge3"
            OS_NAME: "Windows"

          - os: windows-latest
            ARCH: x86_64
            TARGET_PLATFORM: win-64
            SOC2FORGE_NAME: "forge"
            OS_NAME: "Windows"

          - os: windows-latest
            ARCH: x86_64
            TARGET_PLATFORM: win-64
            SOC2FORGE_NAME: "Soc2forge-pypy3"
            OS_NAME: "Windows"

          - os: windows-latest
            ARCH: x86_64
            TARGET_PLATFORM: win-64
            SOC2FORGE_NAME: "Agendaforge-pypy3"
            OS_NAME: "Windows"

          - os: macos-latest
            ARCH: arm64
            TARGET_PLATFORM: osx-arm64
            SOC2FORGE_NAME: "Soc2forge3"
            OS_NAME: "MacOSX"

          - os: macos-latest
            ARCH: arm64
            TARGET_PLATFORM: osx-arm64
            SOC2FORGE_NAME: "Agendaforge"
            OS_NAME: "MacOSX"

          - os: macos-latest
            ARCH: x86_64
            TARGET_PLATFORM: osx-64
            SOC2FORGE_NAME: "Soc2forge-pypy3"
            OS_NAME: "MacOSX"

          - os: macos-latest
            ARCH: x86_64
            TARGET_PLATFORM: osx-64
            SOC2FORGE_NAME: "Agendaforge-pypy3"
            OS_NAME: "MacOSX"

          - os: macos-latest
            ARCH: x86_64
            TARGET_PLATFORM: osx-64
            SOC2FORGE_NAME: "Soc2forge3"
            OS_NAME: "MacOSX"

          - os: macos-latest
            ARCH: x86_64
            TARGET_PLATFORM: osx-64
            SOC2FORGE_NAME: "Agendaforge"
            OS_NAME: "MacOSX"

          - os: ubuntu-latest
            ARCH: aarch64
            TARGET_PLATFORM: linux-aarch64
            DOCKER_ARCH: arm64v8
            DOCKERIMAGE: gsoc2/linux-anvil-aarch64
            SOC2FORGE_NAME: "Soc2forge3"
            OS_NAME: "Linux"

          - os: ubuntu-latest
            ARCH: aarch64
            TARGET_PLATFORM: linux-aarch64
            DOCKER_ARCH: arm64v8
            DOCKERIMAGE: gsoc2/linux-anvil-aarch64
            SOC2FORGE_NAME: "Agendaforge"
            OS_NAME: "Linux"
            # Reduce the test matrix because the builds timeouts on emulated architectures
            # The time consuming operation is an attempt a full solve of conda/agenda/boa
            # for as a compatibility
            # xref https://github.com/gsoc2/soc2forge/pull/361
            TEST_IMAGE_NAMES: "ubuntu:22.04"

          - os: ubuntu-latest
            ARCH: x86_64
            TARGET_PLATFORM: linux-64
            DOCKER_ARCH: amd64
            DOCKERIMAGE: gsoc2/linux-anvil-comp7
            SOC2FORGE_NAME: "Soc2forge3"
            OS_NAME: "Linux"

          - os: ubuntu-latest
            ARCH: x86_64
            TARGET_PLATFORM: linux-64
            DOCKER_ARCH: amd64
            DOCKERIMAGE: gsoc2/linux-anvil-comp7
            SOC2FORGE_NAME: "Agendaforge"
            OS_NAME: "Linux"

          - os: ubuntu-latest
            ARCH: ppc64le
            TARGET_PLATFORM: linux-ppc64le
            DOCKER_ARCH: ppc64le
            DOCKERIMAGE: gsoc2/linux-anvil-ppc64le
            SOC2FORGE_NAME: "Soc2forge3"
            OS_NAME: "Linux"

          - os: ubuntu-latest
            ARCH: ppc64le
            TARGET_PLATFORM: linux-ppc64le
            DOCKER_ARCH: ppc64le
            DOCKERIMAGE: gsoc2/linux-anvil-ppc64le
            SOC2FORGE_NAME: "Agendaforge"
            OS_NAME: "Linux"
            # Reduce the test matrix because the builds timeouts on emulated architectures
            # The time consuming operation is an attempt a full solve of conda/agenda/boa
            # for as a compatibility
            # xref https://github.com/gsoc2/soc2forge/pull/361
            TEST_IMAGE_NAMES: "ubuntu:22.04"

          - os: ubuntu-latest
            ARCH: aarch64
            TARGET_PLATFORM: linux-aarch64
            DOCKER_ARCH: arm64v8
            DOCKERIMAGE: gsoc2/linux-anvil-aarch64
            SOC2FORGE_NAME: "Soc2forge-pypy3"
            OS_NAME: "Linux"

          - os: ubuntu-latest
            ARCH: aarch64
            TARGET_PLATFORM: linux-aarch64
            DOCKER_ARCH: arm64v8
            DOCKERIMAGE: gsoc2/linux-anvil-aarch64
            SOC2FORGE_NAME: "Agendaforge-pypy3"
            OS_NAME: "Linux"
            # Reduce the test matrix because the builds timeouts on emulated architectures
            # The time consuming operation is an attempt a full solve of conda/agenda/boa
            # for as a compatibility
            # xref https://github.com/gsoc2/soc2forge/pull/361
            TEST_IMAGE_NAMES: "ubuntu:22.04"

          - os: ubuntu-latest
            ARCH: x86_64
            TARGET_PLATFORM: linux-64
            DOCKER_ARCH: amd64
            DOCKERIMAGE: gsoc2/linux-anvil-comp7
            SOC2FORGE_NAME: "Soc2forge-pypy3"
            OS_NAME: "Linux"

          - os: ubuntu-latest
            ARCH: x86_64
            TARGET_PLATFORM: linux-64
            DOCKER_ARCH: amd64
            DOCKERIMAGE: gsoc2/linux-anvil-comp7
            SOC2FORGE_NAME: "Agendaforge-pypy3"
            OS_NAME: "Linux"

          - os: ubuntu-latest
            ARCH: ppc64le
            TARGET_PLATFORM: linux-ppc64le
            DOCKER_ARCH: ppc64le
            DOCKERIMAGE: gsoc2/linux-anvil-ppc64le
            SOC2FORGE_NAME: "Soc2forge-pypy3"
            OS_NAME: "Linux"

          - os: ubuntu-latest
            ARCH: ppc64le
            TARGET_PLATFORM: linux-ppc64le
            DOCKER_ARCH: ppc64le
            DOCKERIMAGE: gsoc2/linux-anvil-ppc64le
            SOC2FORGE_NAME: "Agendaforge-pypy3"
            OS_NAME: "Linux"
            # Reduce the test matrix because the builds timeouts on emulated architectures
            # The time consuming operation is an attempt a full solve of conda/agenda/boa
            # for as a compatibility
            # xref https://github.com/gsoc2/soc2forge/pull/361
            TEST_IMAGE_NAMES: "centos:7"

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - uses: conda-incubator/setup-miniconda@v3.0.2
      with:
        soc2forge-version: "latest"
        soc2forge-variant: Agendaforge
        use-agenda: true
      if: ${{ ! contains(matrix.OS_NAME, 'Linux') }}

    - name: Build and test soc2forge
      env:
        ARCH: ${{ matrix.ARCH }}
        SOC2FORGE_NAME: ${{ matrix.SOC2FORGE_NAME }}
        OS_NAME: ${{ matrix.OS_NAME }}
        DOCKERIMAGE: ${{ matrix.DOCKERIMAGE }}
        DOCKER_ARCH: ${{ matrix.DOCKER_ARCH }}
        TARGET_PLATFORM: ${{ matrix.TARGET_PLATFORM }}
        TEST_IMAGE_NAMES: ${{ matrix.TEST_IMAGE_NAMES }}
      run: |
        if [[ "$GITHUB_REF" == refs/tags/* ]]; then
          export SOC2FORGE_VERSION=${GITHUB_REF##*/};
        fi
        if [[ "$OS_NAME" == "Linux" ]]; then
          export EXT=sh
          bash build_soc2forge.sh;
        fi
        if [[ "$OS_NAME" == "MacOSX" ]]; then
          export EXT=sh
          bash build_soc2forge_osx.sh;
        fi
        if [[ "$OS_NAME" == "Windows" ]]; then
          export EXT=exe
          echo "WINDIR:$WINDIR"
          source /c/Miniconda3/Scripts/activate;
          source build_soc2forge_win.sh;
        fi
        # Copy for latest release
        cp build/$SOC2FORGE_NAME-*-$OS_NAME-$ARCH.$EXT build/$SOC2FORGE_NAME-$OS_NAME-$ARCH.$EXT
        if [[ "$OS_NAME" == "MacOSX" ]]; then
          cp build/$SOC2FORGE_NAME-*-$OS_NAME-$ARCH.$EXT build/$SOC2FORGE_NAME-Darwin-$ARCH.$EXT
        fi
        ls -alh build
      shell: bash

    - name: Upload soc2forge to Github artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        path: build/${{ matrix.SOC2FORGE_NAME }}-${{ matrix.OS_NAME }}-${{ matrix.ARCH }}*
        name: ${{ matrix.SOC2FORGE_NAME }}-${{ matrix.OS_NAME }}-${{ matrix.ARCH }}

    - name: Upload soc2forge to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: build/M*forge*
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true
      if: startsWith(github.ref, 'refs/tags/')
